version: '3'

services:
  app:
    container_name: truncate-app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "443:443"
    depends_on:
      - db
    networks:
      - net
  db:
    container_name: truncate-db
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - net
    volumes:
      - database:/var/lib/postgresql/data

networks:
  net:
    driver: bridge

volumes:
  database:
    driver: local